name: Build Binary

on:
  push:
    paths:
      - "utilities/quiz.py"
      - ".github/workflows/binary.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          check-latest: true

      - name: Set up Virtual Environment
        run: |
          python -m venv venv
          .\venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Binary
        id: create-binary
        run: .\venv\Scripts\python utilities\create-binary.py

      - name: Generate checksums
        shell: pwsh
        run: |
          $sha256 = (Get-FileHash -Path "ecs-quiz.exe" -Algorithm SHA256).Hash
          $sha512 = (Get-FileHash -Path "ecs-quiz.exe" -Algorithm SHA512).Hash

          Set-Content -Path "SHA256SUMS" -Value $sha256
          Set-Content -Path "SHA512SUMS" -Value $sha512

          "SHA256SUMS=$sha256" | Out-File -FilePath $env:GITHUB_ENV -Append
          "SHA512SUMS=$sha512" | Out-File -FilePath $env:GITHUB_ENV -Append

      - uses: actions/attest-build-provenance@v2
        id: attest_url
        with:
          subject-path: ecs-quiz.exe

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: ecs-quiz.exe

      - name: Generate Version
        shell: pwsh
        run: |
          $version = (Get-Date).ToUniversalTime().ToString("yyyy.MM.dd.HHmm")
          $buildDate = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss UTC")
          "VERSION=$version" >> $env:GITHUB_ENV
          "BUILD_DATE=$buildDate" >> $env:GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          files: |
            ecs-quiz.exe
            SHA256SUMS
            SHA512SUMS
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            Build Date: ${{ env.BUILD_DATE }}

            Attestation: ${{ steps.attest_url.outputs.attestation-url }}

            Virustotal: https://www.virustotal.com/gui/file/${{ env.SHA256SUMS }}/detection

            > [!NOTE]
            > There are false positives on VirusTotal. The binary is safe to use and it is just flagged by some for being a generic pyinstaller exe. All the major vendors have marked it as safe.
            >
            > The code the exe is based on is opensource here via `quiz.py` and the build process is transparent.

            SHA-256 Checksum:
            ```
            ${{ env.SHA256SUMS }}
            ```

            SHA-512 Checksum:
            ```
            ${{ env.SHA512SUMS }}
            ```
          draft: false
          prerelease: false
