name: Build Binary

on:
  workflow_dispatch:
  push:
    paths:
      - "utilities/quiz.py"
      - ".github/workflows/binary.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          check-latest: true

      - name: Set up Virtual Environment
        run: |
          python -m venv venv
          .\venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Binary
        id: create-binary
        run: .\venv\Scripts\python utilities\create-binary.py

      - name: Generate checksums
        run: |
          certutil -hashfile ecs-quiz.exe SHA256 > SHA256SUMS
          certutil -hashfile ecs-quiz.exe SHA512 > SHA512SUMS

      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: ecs-quiz.exe

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: ecs-quiz.exe

      - name: Generate Version
        shell: pwsh
        run: |
          $version = (Get-Date).ToUniversalTime().ToString("yyyy.MM.dd.HHmm")
          $buildDate = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss UTC")
          "VERSION=$version" >> $env:GITHUB_ENV
          "BUILD_DATE=$buildDate" >> $env:GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          files: |
            ecs-quiz.exe
            SHA256SUMS
            SHA512SUMS
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            Build Date: ${{ env.BUILD_DATE }}

            SHA-256 Checksum:

            ```
            $(cat SHA256SUMS)
            ```

            SHA-512 Checksum:

            ```
            $(cat SHA512SUMS)
            ```
          draft: false
          prerelease: false

      - name: Commit and Push
        if: success()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ecs-quiz.exe SHA256SUMS SHA512SUMS
          git commit -m "Auto-build binary v${{ env.VERSION }}"
          git tag -a v${{ env.VERSION }} -m "Release v${{ env.VERSION }}"
          git push origin v${{ env.VERSION }}
          git push
